import {ArrowUpRight,Check,MapPin} from 'lucide-react';
import {Shell,ButtonLink,TextLink,TrustStrip} from '@/components/site-shell';
import {QuoteForm} from '@/components/contact';
import {ApplicationShowcase} from '@/components/application-showcase';
import content from '@/lib/content.json';
import {TurfSelector} from '@/components/turf-selector';
export default function Home(){return <Shell cta={false}>
<section className="garden-hero">
 <div className="garden-hero-photo"><video src="/assets/hero_vid.mp4" poster="/assets/lawn.webp" autoPlay muted loop playsInline preload="metadata" aria-label="A lush green lawn beside a landscaped garden"/></div>
 <div className="hero-left-scrim" aria-hidden="true"/>
 <div className="hero-editorial-card"><span className="eyebrow"><span className="tiny-rule"/>A greener way to live</span><h1>Beautiful grass.<br/><em>Better living.</em></h1><p>Premium artificial turf for the places you call your own. Thoughtfully selected. Expertly installed.</p><ButtonLink href="/products-gator-turf/">Explore our turf</ButtonLink><a href="/contact/" className="hero-consult">Start with a free consultation <ArrowUpRight size={16}/></a></div>
 <div className="hero-location"><MapPin size={16}/><span>Made for life in Florida</span></div>
 <div className="hero-bottom-note"><span>SUPPLY · INSTALLATION · MAINTENANCE</span><a href="#the-difference">Discover the difference <span>↓</span></a></div>
</section>
<section className="container material-story" id="the-difference"><div className="material-copy"><span className="section-index">01 / THE GATOR TURF DIFFERENCE</span><h2>Feels right.<br/>Looks natural.<br/><span>Lives beautifully.</span></h2><div className="material-detail"><span>Every fiber. Every finish.</span><small>BERMUDA PRO / THE TURF COLLECTION</small></div><p>It’s the little details that make a space feel like yours. The shade of green. The softness underfoot. The way every edge comes together.</p><p>We pair quality products with careful installation, helping you create a space you’ll love for years to come.</p><ul className="quality-list"><li><Check/>Premium turf selection</li><li><Check/>Professional installation</li><li><Check/>15-year material warranty</li></ul><TextLink href="/about/">Get to know Gator Turf</TextLink></div><div className="material-display"><span className="material-word">Naturally<br/><em>inviting.</em></span><img src={content.products[2].image} alt="Close-up profile of Bermuda Pro artificial turf" loading="lazy"/><img className="material-soil" src="/assets/soil-texture.png" alt="" loading="lazy"/><a className="material-chip" href="/product/bermuda-pro/"><span>100<small>oz</small></span><span>Meet Bermuda Pro <ArrowUpRight size={17}/></span></a></div></section>
<TrustStrip/>
<TurfSelector products={[1,2,6].map(i=>{const {title,path,image,weight}=content.products[i];return {title,path,image,weight}})}/>
<ApplicationShowcase/>
<section id="our-work" className="container section project-editorial"><div className="project-intro"><span className="section-index">04 / OUR WORK, OUTDOORS</span><h2>From possibility<br/>to <span>your favorite place.</span></h2><p>Room to relax. Space to play. Explore real outdoor spaces transformed with thoughtfully selected turf and a finish made for everyday life.</p><TextLink href="/gallery/">Discover our projects</TextLink></div><div className="project-diptych"><a href="/gallery/lawn-landscaping/" className="project-major"><img src="/assets/hero.webp" alt="A rooftop terrace transformed with artificial turf" loading="lazy"/><div><span>LAWNS & LANDSCAPING</span><h3>Fresh air. A fresh perspective.</h3><ArrowUpRight/></div></a><a href="/gallery/pets/" className="project-minor"><img src="/assets/pets.webp" alt="A dog enjoying a low-maintenance turf yard" loading="lazy"/><div><span>SPACES FOR EVERYONE</span><h3>Room for a little more play.</h3><ArrowUpRight/></div></a></div></section>
<section className="home-faq-section"><div className="container section home-faq-layout"><div><span className="section-index">05 / KNOW YOUR TURF</span><h2>A little clarity<br/>before <span>you go green.</span></h2><p>Good decisions start with the right questions.</p><TextLink href="/faqs/">All your questions, answered</TextLink></div><div className="home-faq-list">{content.faqs.slice(0,5).map((f,i)=><details className="faq-item" key={f.question} open={i===0}><summary><span className="faq-number">0{i+1}</span><span>{f.question}</span></summary><p>{f.answer}</p></details>)}</div></div></section>
<section id="enquiry" className="container section home-enquiry"><div className="enquiry-pitch"><img className="enquiry-backdrop" src="/assets/hero.webp" alt="A green rooftop lawn with an open Florida horizon" loading="lazy"/><div className="enquiry-overlay"><span className="section-index">LET’S BRING IT TO LIFE</span><h2>Your next chapter<br/>starts <span>outside.</span></h2><p>A little inspiration. A few samples. A conversation about what’s possible. Let’s find your green.</p><a className="enquiry-phone" href="tel:+19545108873">Prefer a conversation?<strong>954.510.8873</strong></a></div></div><QuoteForm/></section>
</Shell>}
