"use client";
import {useState,useEffect} from 'react';
import {registerCatalogTool} from '@/lib/catalog-agent';
import {ArrowUpRight,SlidersHorizontal,Search,X} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {ButtonLink} from '@/components/site-shell';
export type Product={title:string,path:string,image:string,weight:string,tags:string[],specs:string[],features:string[],images:string[]};
type Filters=Record<string,{value:string,label:string}[]>;
export function ProductCard({product}:{product:Product}){return <a href={product.path} className="product-card"><div className="product-photo"><img src={product.image} alt={product.title+' turf sample'} loading="lazy"/><span className="product-type">{product.tags.includes('ivy-walls')?'Hedge collection':'Turf collection'}</span></div><div className="card-title"><h3>{product.title}</h3><ArrowUpRight/></div><p>{product.weight}<span>Explore product</span></p></a>}
export function Catalog({products,filters,category='all'}:{products:Product[],filters:Filters,category?:string}){const [selected,setSelected]=useState<Record<string,string>>({application:'all',weight:'all',space:'all',color:'all'});useEffect(()=>registerCatalogTool(products,filters,setSelected),[products,filters]);const filtered=products.filter(p=>Object.values(selected).every(v=>v==='all'||p.tags.includes(v)));const changed=Object.values(selected).some(v=>v!=='all');return <div className="catalog"><div className="filter-bar"><span className="filter-title"><SlidersHorizontal size={17}/> Refine your selection</span><div className="filter-controls">{Object.entries(filters).map(([key,options])=><Select key={key} value={selected[key]||'all'} onValueChange={v=>setSelected({...selected,[key]:v})}><SelectTrigger className="catalog-select" aria-label={'Filter by '+key}><SelectValue/></SelectTrigger><SelectContent>{options.filter((v,i,a)=>a.findIndex(q=>q.value===v.value)===i).map(o=><SelectItem key={o.value} value={o.value}>{o.value==='all'?'All '+({application:'applications',weight:'weights',space:'sizes',color:'colors'}[key]):o.label}</SelectItem>)}</SelectContent></Select>)}{changed&&<button className="clear-filter" onClick={()=>setSelected({application:'all',weight:'all',space:'all',color:'all'})} aria-label="Reset product filters"><X size={16}/>Reset</button>}</div></div><div className="catalog-result" aria-live="polite"><span>{filtered.length} {filtered.length===1?'product':'products'}</span><span>Find a feel. Find your finish.</span></div>{filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard product={p} key={p.path}/>)}</div>:<div className="empty-state"><SlidersHorizontal/><h3>No products match these filters.</h3><p>Try a different combination to explore more options.</p><button className="button outline" onClick={()=>setSelected({application:'all',weight:'all',space:'all',color:'all'})}>Clear all filters</button></div>}</div>}
export function ProductDetail({product}:{product:Product}){const images=product.images.length?product.images:[product.image];const [index,setIndex]=useState(0);return <div className="product-detail"><div><div className="detail-photo"><img src={images[index]} alt={product.title+' sample, view '+(index+1)}/></div>{images.length>1&&<div className="product-thumbs">{images.map((src,i)=><button key={src} className={index===i?'selected':''} onClick={()=>setIndex(i)} aria-label={'View sample '+(i+1)} aria-pressed={index===i}><img src={src} alt=""/></button>)}</div>}</div><div className="product-info"><span className="eyebrow">{product.tags.includes('ivy-walls')?'The hedge collection':'The turf collection'}</span><h1>{product.title}</h1><p className="product-subtitle">{product.tags.includes('ivy-walls')?'A fresh layer of texture and greenery for your vertical spaces.':'A greener foundation for your outdoor space.'}</p><div className="spec-list">{product.specs.map((spec,i)=>{const split=spec.indexOf(':');return <div key={i}><span>{split>0?spec.slice(0,split):'Specification'}</span><p>{split>0?spec.slice(split+1).trim():spec}</p></div>})}{!product.specs.length&&<div><span>Collection</span><p>{product.weight}</p></div>}</div><ButtonLink href={'/contact/?product='+encodeURIComponent(product.title)}>Request a quote & samples</ButtonLink><p className="sample-note">See the color. Feel the difference. Ask our team for samples.</p>{product.features.length>0&&<div className="features"><h3>The finer details</h3><ul>{product.features.map(f=><li key={f}>{f.toLowerCase()}</li>)}</ul></div>}</div></div>}
