"use client";
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Menu,X,Search,ShieldCheck,Award,Sprout,House,ChevronRight,MapPin,Mail} from 'lucide-react';
import {applications,offices} from '@/lib/brand';
import {ChatWidget} from '@/components/chat-widget';
export function ButtonLink({href,children,variant=''}:{href:string,children:React.ReactNode,variant?:string}){return <a className={`button ${variant}`} href={href}>{children}<ArrowUpRight aria-hidden="true"/></a>}
export function TextLink({href,children}:{href:string,children:React.ReactNode}){return <a className="text-link" href={href}>{children}<ArrowRight aria-hidden="true"/></a>}
const nav=[['Applications','/applications/'],['Products','/products-gator-turf/'],['Contact','/contact/'],['Pay online','/pay-online/']];
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();const [atFooter,setAtFooter]=useState(false);
useEffect(()=>{setOpen(false);},[path]);
useEffect(()=>{const footer=document.querySelector('footer.footer');if(!footer)return;const update=()=>{const at=footer.getBoundingClientRect().top<=window.innerHeight;setAtFooter(at);if(at)setOpen(false);};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[path]);
return <><a className="skip" href="#main">Skip to content</a><header inert={atFooter} className={"header "+(path==='/'?'header-home':'header-inner')+(open?' menu-open':'')+(atFooter?' is-hidden':'')}><div className="nav"><a className="logo" href="/" aria-label="Gator Turf home"><img src="/assets/logo.png" alt="Gator Turf"/></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,url])=><a key={url} href={url} className={path.startsWith(url.slice(0,-1))?'active':undefined}>{name}</a>)}</nav><a className="nav-search" href="/products-gator-turf/" aria-label="Search our products"><Search aria-hidden="true"/></a><div className="nav-contact"><span className="nav-contact-title">Get in touch with us</span>{offices.map(o=><a key={o.name} href={'tel:'+o.tel}><span>{o.name}</span><strong>{o.phone}{o.phone.endsWith('8873')?' (TURF)':''}</strong></a>)}</div><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{nav.map(([name,url])=><a key={url} href={url} onClick={()=>setOpen(false)}>{name}</a>)}<a href="/gallery/">Our work</a><a href="/about/">About</a><a href="/blog/">Journal</a><div className="mobile-contact">{offices.map(o=><a key={o.name} href={'tel:'+o.tel}>{o.name} <strong>{o.phone}</strong></a>)}</div><ButtonLink href="/contact/">Get a free quote</ButtonLink></nav>}</header></>}
export function TrustStrip(){return <div className="container trust-strip">{[[ShieldCheck,'15-year','Material warranty'],[Award,'American quality','Products you can trust'],[Sprout,'Expert installation','From start to finish'],[House,'Home Depot','Service provider']].map(([Icon,title,desc]:any)=><div className="trust-item" key={title}><Icon aria-hidden="true"/><div><strong>{title}</strong><span>{desc}</span></div></div>)}</div>}
export function CTA(){return <section className="cta"><img src="/assets/garden.webp" alt="" className="cta-background" loading="lazy"/><div><span className="eyebrow">Your outdoors, reimagined</span><h2>A greener space.<br/>A better everyday.</h2><p>Let’s find the right turf for the way you live.</p></div><ButtonLink href="/contact/" variant="light">Get your free quote</ButtonLink></section>}

const footerAbout=[['About Our Products','/about/'],['Gallery','/gallery/'],['Blog','/blog/'],['Get a Quote','/contact/'],['Pay Online','/pay-online/']];
const footerApplications=[['Lawn & Landscaping','lawn-landscaping'],['Golf','artificial-grass-for-golf-courses'],['Pets','pets'],['Athletics & Playground','athletics-playground'],['Ivy Walls','ivy-walls']];
const footerProducts=[['Commercial','/product_categories/commercial/'],['Residential','/product_categories/residential/'],['Hedge Mats','/product_categories/hedge-mats/'],['Topiary Ball','/product_categories/topiary-ball/']];
const socialLinks:[string,string,(props:{'aria-hidden'?:boolean})=>React.ReactElement][]=[
['Facebook','https://www.facebook.com/ArtificialGatorTurf',(p)=><svg {...p} viewBox="0 0 24 24" fill="currentColor"><path d="M15.12 8.4H13V6.6c0-.68.45-.84.77-.84h2.3V2.5L13.03 2.5C10.1 2.5 9.43 4.68 9.43 6.42V8.4H7.5v3.6h1.93V21.5H13v-9.5h2.62l.34-3.6z"/></svg>],
['Twitter','#',(p)=><svg {...p} viewBox="0 0 24 24" fill="currentColor"><path d="M22 5.92c-.74.33-1.53.55-2.36.65a4.1 4.1 0 0 0 1.8-2.27 8.2 8.2 0 0 1-2.6 1 4.1 4.1 0 0 0-7 3.74A11.6 11.6 0 0 1 3.4 4.6a4.1 4.1 0 0 0 1.27 5.47 4.1 4.1 0 0 1-1.86-.51v.05a4.1 4.1 0 0 0 3.29 4.02 4.1 4.1 0 0 1-1.85.07 4.1 4.1 0 0 0 3.83 2.85A8.24 8.24 0 0 1 2 18.58a11.63 11.63 0 0 0 6.29 1.84c7.55 0 11.68-6.26 11.68-11.69l-.01-.53A8.3 8.3 0 0 0 22 5.92z"/></svg>],
['Instagram','https://www.instagram.com/gator_turf',(p)=><svg {...p} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.2" cy="6.8" r="1" fill="currentColor" stroke="none"/></svg>],
['Pinterest','#',(p)=><svg {...p} viewBox="0 0 24 24" fill="currentColor"><path d="M12 2a10 10 0 0 0-3.64 19.32c-.05-.82-.1-2.08.02-2.98.11-.8 1.42-6.08 1.42-6.08s-.36-.73-.36-1.8c0-1.68.98-2.94 2.19-2.94 1.03 0 1.53.78 1.53 1.7 0 1.04-.66 2.6-1 4.04-.29 1.21.6 2.2 1.8 2.2 2.16 0 3.6-2.77 3.6-6.06 0-2.5-1.68-4.37-4.74-4.37-3.45 0-5.6 2.58-5.6 5.45 0 .99.29 1.69.75 2.23.21.25.24.35.16.63-.05.21-.18.73-.23.93-.08.3-.3.4-.56.29-1.56-.64-2.29-2.35-2.29-4.27 0-3.18 2.68-6.98 7.98-6.98 4.26 0 7.07 3.08 7.07 6.39 0 4.37-2.42 7.64-5.99 7.64-1.2 0-2.33-.65-2.72-1.38 0 0-.65 2.6-.78 3.1-.23.88-.69 1.76-1.11 2.45A10 10 0 1 0 12 2z"/></svg>],
];
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-head"><a href="/" className="footer-brand"><img className="footer-logo" src="/assets/logo-white.png" alt="Gator Turf"/></a><span className="footer-rule" aria-hidden="true"/><div className="footer-social">{socialLinks.map(([name,href,Icon])=><a key={name} href={href} aria-label={'Gator Turf on '+name}><Icon aria-hidden/></a>)}</div></div><div className="footer-top"><div className="footer-locations">{offices.map(o=><div className="footer-office" key={o.name}><MapPin aria-hidden="true"/><div><strong>{o.name}</strong><span>{o.address}</span><span>{o.city}</span><a href={'tel:'+o.tel}>{o.phone}{o.phone.endsWith('8873')?' (TURF)':''}</a></div></div>)}<div className="footer-office footer-email"><Mail aria-hidden="true"/><div><strong>Email us:</strong><a href="mailto:sales@gatorturf.net">sales@gatorturf.net</a></div></div></div><div><h3>About</h3>{footerAbout.map(([name,href])=><a key={name} href={href}>{name}</a>)}</div><div><h3>Applications</h3>{footerApplications.map(([name,slug])=><a key={slug} href={'/applications/'+slug+'/'}>{name}</a>)}</div><div><h3>Products</h3>{footerProducts.map(([name,href])=><a key={name} href={href}>{name}</a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Gator Turf. All rights reserved.</span></div><div className="footer-wordmark" aria-hidden="true"><svg viewBox="0 38 1000 128" role="presentation" focusable="false"><text x="0" y="200" textLength="1000" lengthAdjust="spacing">Gator Turf</text></svg></div></div></footer>}
export function Shell({children,cta=true}:{children:React.ReactNode,cta?:boolean}){return <><Header/><main id="main">{children}</main>{cta&&<CTA/>}<Footer/><ChatWidget/></>}
export function Breadcrumb({title,parent}:{title:string,parent?:{name:string,href:string}}){return <nav className="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight/>{parent&&<><a href={parent.href}>{parent.name}</a><ChevronRight/></>}<span aria-current="page">{title}</span></nav>}
export function PageIntro({eyebrow,title,description}:{eyebrow:string,title:string,description?:string}){return <div className="page-intro"><div className="intro-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{description&&<div className="intro-description"><span className="intro-line"/><p>{description}</p></div>}</div>}
export function ApplicationCard({app,index=0}:{app:typeof applications[number],index?:number}){return <a className="application-card" href={'/applications/'+app.slug+'/'}><div className="photo"><img src={app.image} alt={app.name} loading="lazy"/><span className="application-number">0{index+1}</span></div><div className="card-title"><h3>{app.name}</h3><ArrowUpRight/></div><p>{app.description}</p></a>}
