"use client";
import {useState,useEffect} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Menu,X,Search,ShieldCheck,Award,Sprout,House,ChevronRight} from 'lucide-react';
import {applications,offices} from '@/lib/brand';
import {ChatWidget} from '@/components/chat-widget';
export function ButtonLink({href,children,variant=''}:{href:string,children:React.ReactNode,variant?:string}){return <a className={`button ${variant}`} href={href}>{children}<ArrowUpRight aria-hidden="true"/></a>}
export function TextLink({href,children}:{href:string,children:React.ReactNode}){return <a className="text-link" href={href}>{children}<ArrowRight aria-hidden="true"/></a>}
const nav=[['Applications','/applications/'],['Products','/products-gator-turf/'],['Contact','/contact/'],['Pay online','/pay-online/']];
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();const [atFooter,setAtFooter]=useState(false);
useEffect(()=>{setOpen(false);},[path]);
useEffect(()=>{const footer=document.querySelector('footer.footer');if(!footer)return;const update=()=>{const at=footer.getBoundingClientRect().top<=window.innerHeight;setAtFooter(at);if(at)setOpen(false);};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update);};},[path]);
return <><a className="skip" href="#main">Skip to content</a><header inert={atFooter} className={"header "+(path==='/'?'header-home':'header-inner')+(open?' menu-open':'')+(atFooter?' is-hidden':'')}><div className="nav"><a className="logo" href="/" aria-label="Gator Turf home"><img src="/assets/logo.png" alt="Gator Turf"/></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([name,url])=><a key={url} href={url} className={path.startsWith(url.slice(0,-1))?'active':undefined}>{name}</a>)}</nav><a className="nav-search" href="/products-gator-turf/" aria-label="Search our products"><Search aria-hidden="true"/></a><div className="nav-contact"><span className="nav-contact-title">Get in touch with us</span>{offices.map(o=><a key={o.name} href={'tel:'+o.tel}><span>{o.name}</span><strong>{o.phone}{o.phone.endsWith('8873')?' (TURF)':''}</strong></a>)}</div><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Mobile navigation">{nav.map(([name,url])=><a key={url} href={url} onClick={()=>setOpen(false)}>{name}</a>)}<a href="/gallery/">Our work</a><a href="/about/">About</a><a href="/blog/">Journal</a><div className="mobile-contact">{offices.map(o=><a key={o.name} href={'tel:'+o.tel}>{o.name} <strong>{o.phone}</strong></a>)}</div><ButtonLink href="/contact/">Get a free quote</ButtonLink></nav>}</header></>}
export function TrustStrip(){return <div className="container trust-strip">{[[ShieldCheck,'15-year','Material warranty'],[Award,'American quality','Products you can trust'],[Sprout,'Expert installation','From start to finish'],[House,'Home Depot','Service provider']].map(([Icon,title,desc]:any)=><div className="trust-item" key={title}><Icon aria-hidden="true"/><div><strong>{title}</strong><span>{desc}</span></div></div>)}</div>}
export function CTA(){return <section className="cta"><img src="/assets/garden.webp" alt="" className="cta-background" loading="lazy"/><div><span className="eyebrow">Your outdoors, reimagined</span><h2>A greener space.<br/>A better everyday.</h2><p>Let’s find the right turf for the way you live.</p></div><ButtonLink href="/contact/" variant="light">Get your free quote</ButtonLink></section>}

export function Footer(){return <footer className="footer"><div className="container"><div className="footer-top"><div><a href="/" className="footer-brand"><img className="footer-logo" src="/assets/logo-white.png" alt="Gator Turf"/></a><p>Beautiful spaces. Less maintenance.<br/>More of the Florida life you love.</p><a href="mailto:sales@gatorturf.net">sales@gatorturf.net</a></div><div><h3>Explore</h3><a href="/about/">About Gator Turf</a><a href="/products-gator-turf/">Our products</a><a href="/gallery/">Our work</a><a href="/blog/">Journal</a><a href="/faqs/">FAQs</a><a href="/pay-online/">Pay online</a></div><div><h3>Find your turf</h3>{applications.map(a=><a href={'/applications/'+a.slug+'/'} key={a.slug}>{a.name}</a>)}<a href="/product_categories/commercial/">Commercial turf</a><a href="/product_categories/residential/">Residential turf</a></div><div><h3>Here in Florida</h3>{offices.map(o=><a key={o.name} href={'tel:'+o.tel}>{o.name}<br/>{o.phone}</a>)}<a href="/service-areas/">View service areas</a><a href="/contact/">Visit a location <span aria-hidden="true">↗</span></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Gator Turf. All rights reserved.</span><span><a href="https://www.instagram.com/gator_turf" style={{display:'inline',margin:0}}>Instagram</a> &nbsp; / &nbsp; <a href="https://www.facebook.com/ArtificialGatorTurf" style={{display:'inline',margin:0}}>Facebook</a></span></div><div className="footer-wordmark" aria-hidden="true"><svg viewBox="0 38 1000 128" role="presentation" focusable="false"><text x="0" y="200" textLength="1000" lengthAdjust="spacing">Gator Turf</text></svg></div></div></footer>}
export function Shell({children,cta=true}:{children:React.ReactNode,cta?:boolean}){return <><Header/><main id="main">{children}</main>{cta&&<CTA/>}<Footer/><ChatWidget/></>}
export function Breadcrumb({title,parent}:{title:string,parent?:{name:string,href:string}}){return <nav className="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight/>{parent&&<><a href={parent.href}>{parent.name}</a><ChevronRight/></>}<span aria-current="page">{title}</span></nav>}
export function PageIntro({eyebrow,title,description}:{eyebrow:string,title:string,description?:string}){return <div className="page-intro"><div className="intro-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{description&&<div className="intro-description"><span className="intro-line"/><p>{description}</p></div>}</div>}
export function ApplicationCard({app,index=0}:{app:typeof applications[number],index?:number}){return <a className="application-card" href={'/applications/'+app.slug+'/'}><div className="photo"><img src={app.image} alt={app.name} loading="lazy"/><span className="application-number">0{index+1}</span></div><div className="card-title"><h3>{app.name}</h3><ArrowUpRight/></div><p>{app.description}</p></a>}
