import type {Metadata} from 'next';
import {notFound,redirect} from 'next/navigation';
import {ArrowUpRight,Phone,Mail,MapPin,ShieldCheck} from 'lucide-react';
import content from '@/lib/content.json';
import payment from '@/lib/payment.json';
import {applications,offices} from '@/lib/brand';
import {Shell,Breadcrumb,PageIntro,ButtonLink,TextLink,TrustStrip,ApplicationCard} from '@/components/site-shell';
import {Catalog,ProductCard,ProductDetail} from '@/components/catalog';
import {Gallery} from '@/components/gallery';
import {Journal} from '@/components/journal';
import {QuoteForm} from '@/components/contact';
const pages=content.pages;
const products=content.products;
const posts=pages.filter(p=>p.type==='post').sort((a,b)=>b.date.localeCompare(a.date));
const categories=[['All products','/products-gator-turf/'],['Residential','/product_categories/residential/'],['Commercial','/product_categories/commercial/'],['Hedge mats','/product_categories/hedge-mats/'],['Topiary ball','/product_categories/topiary-ball/']];
const titles:Record<string,string>={'/applications/':'Turf for the way you live','/products-gator-turf/':'Our products','/contact/':'Get a free quote','/about/':'About Gator Turf','/company/':'About Gator Turf','/gallery/':'Our work','/blog/':'The Gator Turf journal','/faqs/':'Frequently asked questions','/service-areas/':'Florida service areas','/pay-online/':'Pay online'};
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{const {slug}=await params;const path='/'+slug.join('/')+'/';const page=pages.find(p=>p.path===path);const product=products.find(p=>p.path===path);return {title:titles[path]||product?.title||page?.title||'Gator Turf',description:page?.description||'Premium artificial turf, thoughtful installation and outdoor spaces made for Florida living.'}}
function Intro({title,eyebrow,description}:{title:string,eyebrow:string,description?:string}){return <div className="container"><Breadcrumb title={eyebrow}/><PageIntro title={title} eyebrow={eyebrow} description={description}/></div>}
function Related({items=products.slice(0,3)}:{items?:typeof products}){return <section className="container related-products"><div className="section-heading"><div><span className="eyebrow">Explore the collection</span><h2>Find your perfect green.</h2></div><TextLink href="/products-gator-turf/">View all products</TextLink></div><div className="product-grid">{items.slice(0,3).map(p=><ProductCard key={p.path} product={p}/>)}</div></section>}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;const path='/'+slug.join('/')+'/';const aliases:Record<string,string>={'/products/':'/products-gator-turf/','/applications/golf/':'/applications/artificial-grass-for-golf-courses/','/artificial-grass-installers-near-me-in-palm-beach-county-copy/':'/artificial-grass-installers-near-me-in-palm-beach-county/'};if(aliases[path])redirect(aliases[path]);const page=pages.find(p=>p.path===path);const product=products.find(p=>p.path===path);
if(product)return <Shell><div className="container"><Breadcrumb title={product.title} parent={{name:'Products',href:'/products-gator-turf/'}}/><ProductDetail product={product}/><p className="copyright-note" style={{marginTop:-60,marginBottom:65}}>Colors may appear differently on screen. Please request a product sample from our team.</p></div><Related items={products.filter(p=>p.path!==path&&p.tags.includes('ivy-walls')===product.tags.includes('ivy-walls'))}/></Shell>;
if(path==='/applications/')return <Shell><Intro eyebrow="Our applications" title="Turf for the way you live." description="A quiet morning in the garden. A perfect putt. A place for the whole family to play. There’s a green for every kind of outdoors."/><div className="container all-applications">{applications.map((app,i)=><ApplicationCard app={app} index={i} key={app.slug}/>)}</div><TrustStrip/></Shell>;
const app=applications.find(a=>path==='/applications/'+a.slug+'/');
if(app)return <Shell><div className="container"><Breadcrumb title={app.name} parent={{name:'Applications',href:'/applications/'}}/><section className="application-hero"><div><span className="eyebrow">{app.name}</span><h1>{app.title}</h1><p>{app.description}</p><ButtonLink href="/contact/">Let’s plan your space</ButtonLink></div><img src={app.image} alt={app.name}/></section></div><TrustStrip/><div className="container application-copy"><div><span className="eyebrow">Made for your everyday</span><h2>{app.short}.</h2></div><div className="article-body" dangerouslySetInnerHTML={{__html:page?.body||''}}/></div><Related items={products.filter(p=>app.slug==='ivy-walls'?p.tags.includes('ivy-walls'):!p.tags.includes('ivy-walls'))}/></Shell>;
if(path==='/products-gator-turf/'||path.startsWith('/product_categories/')){const cat=slug[1]||'all';const label=categories.find(c=>c[1]===path)?.[0]||'Our products';const subset=(cat==='hedge-mats'||cat==='topiary-ball')?products.filter(p=>p.tags.includes('ivy-walls')):cat==='all'?products:products.filter(p=>!p.tags.includes('ivy-walls'));return <Shell><Intro eyebrow="The Gator Turf collection" title={cat==='all'?'A better kind of green.':label+'. Naturally inviting.'} description={cat==='topiary-ball'?'Explore the greenery collection for topiary projects. Contact our team to discuss the right shape and size for your space.':'Explore textures, tones and finishes for every space. Quality you can see, comfort you can feel.'}/><div className="container"><nav className="category-links" aria-label="Product collections">{categories.map(([n,u])=><a className={path===u?'active':''} href={u} key={u}>{n}</a>)}</nav><Catalog products={subset} filters={content.filters} category={cat}/></div></Shell>}
if(path==='/gallery/'||slug[0]==='gallery'){const names:Record<string,string>={'lawn-landscaping':'Lawn & landscaping',golf:'Golf',pets:'Pets',athletics:'Athletics',playground:'Playground'};const unique=content.gallery.filter((p,i,a)=>a.findIndex(q=>q.image===p.image&&q.category===p.category)===i);return <Shell><Intro eyebrow="Our work" title="Good spaces. Great memories." description="A little inspiration for what comes next. Explore lawns, greens and spaces transformed with Gator Turf."/><div className="container"><Gallery photos={unique} initial={names[slug[1]]||'All projects'}/></div></Shell>}
if(path==='/contact/')return <Shell cta={false}><div className="container"><Breadcrumb title="Contact"/><div className="contact-layout"><div className="contact-copy"><span className="eyebrow">Let’s talk turf</span><h1>Your next great<br/>outdoor space<br/>starts here.</h1><p>From a backyard refresh to a commercial project, our team will help you find the right turf, plan the details and bring it all together.</p><div className="direct-contact"><a href="mailto:sales@gatorturf.net"><Mail/>sales@gatorturf.net</a><a href="tel:+19545108873"><Phone/>954.510.8873</a></div><img src="/assets/hero.webp" className="contact-image" alt="A sunny Florida rooftop with artificial turf"/></div><QuoteForm/></div></div><section className="muted-surface"><div className="container section"><div className="section-heading"><div><span className="eyebrow">Local knowledge. Personal service.</span><h2>Find us in Florida.</h2></div></div><div className="office-grid">{offices.map((o,i)=><div className="office-card" key={o.name}><span>0{i+1}</span><h3>{o.name}</h3><p>{o.address}<br/>{o.city}</p><a href={'tel:'+o.tel}>{o.phone}</a><TextLink href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(o.address+' '+o.city)}>Get directions</TextLink></div>)}</div></div></section></Shell>;
if(path==='/about/'||path==='/company/')return <Shell><div className="container"><Breadcrumb title="About us"/><div className="about-hero"><div><span className="eyebrow">The Gator Turf story</span><h1>A little care.<br/>A lasting difference.</h1><p>We believe your outdoor space should be somewhere you love to spend time. That’s why we pair carefully selected synthetic turf with an installation approach built around your needs.</p><p>From residential landscapes to golf greens, playgrounds and commercial spaces, we help Florida enjoy a greener everyday.</p></div><img src="/assets/about.webp" alt="Careful turf installation by hand"/></div></div><TrustStrip/><section className="green-section"><div className="container section"><span className="eyebrow">From first conversation to final finish</span><h2>Thoughtful from the ground up.</h2><div className="about-values"><div><span>01 / The right fit</span><h3>Your space. Your vision.</h3><p>We take the time to understand your project, your needs and your renovation budget before recommending a solution.</p></div><div><span>02 / The right foundation</span><h3>Quality in every layer.</h3><p>We supply durable synthetic turf and follow careful installation methods to deliver a finish you can enjoy.</p></div><div><span>03 / The long view</span><h3>Care that continues.</h3><p>Alongside supply and installation, Gator Turf offers maintenance services to help keep your space looking its best.</p></div></div></div></section><section className="container section split-section"><img className="split-image" src="/assets/about-2.webp" alt="A dog enjoying a green lawn" loading="lazy"/><div className="split-copy"><span className="eyebrow">Made for living</span><h2>More time for<br/>what matters.</h2><p>Whether your project is a small garden or a large outdoor space, we’re here to help. Our locations in Boca Raton, Tampa and Orlando connect you with a team that understands Florida living.</p><TextLink href="/contact/">Meet your local team</TextLink></div></section></Shell>;
if(path==='/faqs/')return <Shell><Intro eyebrow="A few things to know" title="Your turf questions, answered." description="Get to know the possibilities, the practical details and what to expect from artificial turf."/><div className="container faq-layout"><aside className="faq-aside"><h3>Have another question?</h3><p>Our team can help you choose the right product and plan your project.</p><ButtonLink href="/contact/">Talk to our team</ButtonLink></aside><div>{content.faqs.map((f,i)=><details className="faq-item" key={i}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></div></Shell>;
if(path==='/blog/'||slug[0]==='category'||slug[0]==='tag'||(slug[0]==='blog'&&slug[1]==='page')||/^\d{4}$/.test(slug[0])){let list=posts;let heading='A greener point of view.';if(/^\d{4}$/.test(slug[0]))list=posts.filter(p=>p.date.startsWith(slug[0]+(slug[1]?'-'+slug[1]:'')));if(page?.type==='category'||page?.type==='post_tag'){const linked=posts.filter(p=>page.body.includes(p.path));if(linked.length)list=linked;heading=page.title.replace('Archives','').trim()}return <Shell><Intro eyebrow="The Gator Turf journal" title={heading} description="Practical guides, fresh ideas and a little outdoor inspiration. Make more of your green space."/><div className="container" id="journal"><Journal posts={list.map(({path,title,excerpt,image,date})=>({path,title,excerpt,image,date}))}/></div></Shell>}
if(page?.type==='post'){const words=page.body.replace(/<[^>]*>/g,' ').split(/\s+/).length;return <Shell><div className="container"><Breadcrumb title="Article" parent={{name:'Journal',href:'/blog/'}}/><header className="article-header"><span className="eyebrow">Field notes / Gator Turf</span><h1>{page.title}</h1><div className="article-meta"><span>{page.date?new Date(page.date).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}):'Gator Turf'}</span><span>{Math.max(1,Math.ceil(words/220))} min read</span></div></header>{page.image&&<img className="article-hero" src={page.image} alt={page.title}/>}<div className="article-layout"><div><article className="article-body" dangerouslySetInnerHTML={{__html:page.body}}/><div className="article-back"><TextLink href="/blog/">Back to the journal</TextLink></div></div><aside className="article-aside"><span className="eyebrow">Inspired?</span><h3>Bring your ideas outdoors.</h3><p>Let’s find the right turf for your next project.</p><ButtonLink href="/contact/">Get a free quote</ButtonLink></aside></div></div></Shell>}
if(path==='/service-areas/'){const local=pages.filter(p=>p.type==='page'&&p.path!=='/'&&!['/about/','/contact/','/company/','/applications/','/gallery/','/products-gator-turf/','/blog/','/thank-you/','/faqs/'].includes(p.path)&&!applications.some(a=>p.path==='/applications/'+a.slug+'/'));return <Shell><Intro eyebrow="Our Florida service areas" title="Local expertise. Lasting green." description="Explore turf installation, repair and artificial grass services across Florida. Contact our team to discuss service at your address."/><div className="container service-directory">{local.map(p=><a href={p.path} key={p.path}>{p.title}<ArrowUpRight size={17}/></a>)}</div></Shell>}
if(path==='/pay-online/')return <Shell cta={false}><Intro eyebrow="Customer payments" title="A simple way to settle up."/><div className="payment-card"><ShieldCheck size={40} strokeWidth={1.2}/><h2>Pay securely with Gator Turf.</h2><p>Continue to Gator Turf’s external payment provider. Have your invoice details ready.</p><ButtonLink href={payment.url}>Continue to secure payment</ButtonLink><p style={{fontSize:'.8rem',marginBottom:0}}>Questions about your invoice?<br/><a href="tel:+19545108873">Call 954.510.8873</a></p></div></Shell>;
if(page){return <Shell><div className="container"><Breadcrumb title={page.title}/><div className="service-hero"><span className="eyebrow">Gator Turf / Florida</span><h1>{page.title}</h1><ButtonLink href="/contact/" variant="light">Get your free quote</ButtonLink></div><div className="article-layout"><div className="article-body" dangerouslySetInnerHTML={{__html:page.body}}/><aside className="article-aside"><span className="eyebrow">Our services</span><h3>Find your green.</h3><div className="service-nav">{applications.map(a=><a href={'/applications/'+a.slug+'/'} key={a.slug}>{a.name}</a>)}</div><ButtonLink href="/contact/">Talk to our team</ButtonLink></aside></div></div></Shell>}
notFound();}
